# Day 11 - Dumbo Octopus
1. The energy level of all increases by one
2. Cells with an energy level greater than 9 flash, increasing the level of all adjacent (also diagonal) cells by one. Cells cannot blink twice
3. All blinked cells are reset to 0
4. 

In [95]:
import numpy as np

def parse_input(lines):
    return np.array(
        [[int(i) for i in line.strip()]
            for line in lines]
    )

In [96]:
with open("11_input.in", "r") as f:
    lines = f.readlines()

data = parse_input(lines)

In [97]:
def safe_increment(matrix, position):
    x, y = position
    try:
        matrix[x, y] += 1
    except IndexError:
        pass
    

def run_simulation(initial_state, steps=100):
    state = np.copy(initial_state)
    
    flash_count = 0
    
    # print(state)
    
    for step in range(1, steps+1):
        print(f"---- {step:03d} ----")
        
        state += 1
        
        triggered = np.zeros(shape=state.shape, dtype=np.bool8)
        
        all_flashes_processed = False
        while not all_flashes_processed:
            xs, ys = np.where(state > 9)
            positions_to_trigger = list(zip(xs, ys))
            # print(positions_to_trigger)
            
            txs, tys = np.where(triggered == True)
            positions_triggered = list(zip(txs, tys))
            # print(positions_triggered)
            # print("")
    
            # Break loop once no new positions are found.
            if set(positions_to_trigger).issubset(positions_triggered):
                # print("all triggered!")
                all_flashes_processed = True
                break
    
            for x, y in positions_to_trigger:
                if triggered[x, y]:
                    # Ignore already triggered cells.
                    continue
                
                safe_increment(state, [x-1, y-1])
                safe_increment(state, [x  , y-1])
                safe_increment(state, [x+1, y-1])
                
                safe_increment(state, [x-1, y  ])
                safe_increment(state, [x+1, y  ])
                
                safe_increment(state, [x-1, y+1])
                safe_increment(state, [x  , y+1])
                safe_increment(state, [x+1, y+1])
                
                triggered[x, y] = True
                flash_count += 1
                
        txs, tys = np.where(triggered == True)
        for x, y in zip(txs, tys):
            state[x, y] = 0
            
        # print(state)
            
    return flash_count
        

In [98]:
minimal_example = """
11111
19991
19191
19991
11111
""".splitlines()[1:]

minimal_data = parse_input(minimal_example)

In [108]:
with open("11_input_test.in", "r") as f:
    lines = f.readlines()

test_data = parse_input(lines)

In [99]:
run_simulation(minimal_data, steps=3)

[[1 1 1 1 1]
 [1 9 9 9 1]
 [1 9 1 9 1]
 [1 9 9 9 1]
 [1 1 1 1 1]]
---- 001 ----
[[3 4 5 4 3]
 [4 0 0 0 4]
 [5 0 0 0 5]
 [4 0 0 0 4]
 [3 4 5 4 3]]
---- 002 ----
[[4 5 6 5 4]
 [5 1 1 1 5]
 [6 1 1 1 6]
 [5 1 1 1 5]
 [4 5 6 5 4]]
---- 003 ----
[[5 6 7 6 5]
 [6 2 2 2 6]
 [7 2 2 2 7]
 [6 2 2 2 6]
 [5 6 7 6 5]]


9

In [109]:
res = run_simulation(test_data, steps=100)

[[5 4 8 3 1 4 3 2 2 3]
 [2 7 4 5 8 5 4 7 1 1]
 [5 2 6 4 5 5 6 1 7 3]
 [6 1 4 1 3 3 6 1 4 6]
 [6 3 5 7 3 8 5 4 7 8]
 [4 1 6 7 5 2 4 6 4 5]
 [2 1 7 6 8 4 1 7 2 1]
 [6 8 8 2 8 8 1 1 3 4]
 [4 8 4 6 8 4 8 5 5 4]
 [5 2 8 3 7 5 1 5 2 6]]
---- 001 ----
[[6 5 9 4 2 5 4 3 3 4]
 [3 8 5 6 9 6 5 8 2 2]
 [6 3 7 5 6 6 7 2 8 4]
 [7 2 5 2 4 4 7 2 5 7]
 [7 4 6 8 4 9 6 5 8 9]
 [5 2 7 8 6 3 5 7 5 6]
 [3 2 8 7 9 5 2 8 3 2]
 [7 9 9 3 9 9 2 2 4 5]
 [5 9 5 7 9 5 9 6 6 5]
 [6 3 9 4 8 6 2 6 3 7]]
---- 002 ----
[[8 8 0 7 4 7 6 5 5 5]
 [5 0 8 9 0 8 7 0 5 4]
 [8 5 9 7 8 8 9 6 0 8]
 [8 4 8 5 7 6 9 6 0 0]
 [8 7 0 0 9 0 8 8 0 0]
 [6 6 0 0 0 8 8 9 8 9]
 [6 8 0 0 0 0 5 9 4 4]
 [0 0 0 0 0 0 7 4 5 7]
 [9 0 0 0 0 0 0 8 7 7]
 [8 8 0 0 0 0 6 8 4 8]]
---- 003 ----
[[0 0 5 0 9 0 0 8 6 7]
 [8 5 0 0 8 0 0 5 7 6]
 [9 9 0 0 0 0 0 0 3 9]
 [9 7 0 0 0 0 0 0 4 1]
 [9 9 3 5 0 8 0 0 6 3]
 [7 7 1 2 3 0 0 0 0 0]
 [7 9 1 1 2 5 0 0 0 0]
 [2 2 1 1 1 3 0 0 0 0]
 [0 4 2 1 1 3 6 0 0 0]
 [0 0 4 2 3 4 0 0 0 0]]
---- 004 ----
[[2 2 6 3 0 3 2 0 0 

In [110]:
res

1550